package protocol

// Plan represents an execution plan generated by the Head Agent.
type Plan struct {
	ID          string     `json:"id"`
	Intent      string     `json:"intent"`      // Intent category this plan handles
	Description string     `json:"description"` // Human-readable description
	Steps       []PlanStep `json:"steps"`
	Variables   []Variable `json:"variables"` // Template variables to fill
	CreatedAt   int64      `json:"created_at"`
	UpdatedAt   int64      `json:"updated_at"`
}

// PlanStep represents a single step in an execution plan.
type PlanStep struct {
	ID       int            `json:"id"`
	Subagent string         `json:"subagent"` // Which subagent to use
	Action   string         `json:"action"`   // Action to perform
	Input    map[string]any `json:"input"`    // Input parameters
	Depends  []int          `json:"depends"`  // Step IDs this depends on
	Timeout  int            `json:"timeout"`  // Timeout in seconds
}

// Variable represents a template variable in a reusable plan.
type Variable struct {
	Name        string `json:"name"`
	Type        string `json:"type"` // string, file_path, number, bool
	Description string `json:"description"`
	Required    bool   `json:"required"`
	Default     any    `json:"default,omitempty"`
}

// PlanLibrary represents stored reusable plans.
type PlanLibrary struct {
	Plans     []PlanPattern `json:"plans"`
	Version   int           `json:"version"`
	UpdatedAt int64         `json:"updated_at"`
}

// PlanPattern is a stored plan template that can be reused.
type PlanPattern struct {
	ID             string  `json:"id"`
	IntentCategory string  `json:"intent_category"` // e.g., "code.fix_tests"
	Plan           Plan    `json:"plan"`
	UsageCount     int     `json:"usage_count"`
	SuccessRate    float64 `json:"success_rate"` // 0-1
	LastUsed       int64   `json:"last_used"`
	CreatedAt      int64   `json:"created_at"`
}

// PlanExecution represents an execution of a plan.
type PlanExecution struct {
	ID          string         `json:"id"`
	PlanID      string         `json:"plan_id"`
	Variables   map[string]any `json:"variables"`
	Steps       []StepResult   `json:"steps"`
	Status      string         `json:"status"` // pending, running, completed, failed
	StartedAt   int64          `json:"started_at"`
	CompletedAt int64          `json:"completed_at,omitempty"`
}

// StepResult represents the result of executing a single step.
type StepResult struct {
	StepID     int     `json:"step_id"`
	Success    bool    `json:"success"`
	Data       any     `json:"data,omitempty"`
	Error      string  `json:"error,omitempty"`
	TokensUsed int     `json:"tokens_used"`
	Cost       float64 `json:"cost"`
	DurationMs int64   `json:"duration_ms"`
}
